Repository google/transit, pull requests merged in 2019-07, with the labels that each got.

#165 Arrival and departure time best practices
  gtfs/spec/en/reference.md
Labels: cla: no

#167 Headsign best practices
  gtfs/spec/en/reference.md
Labels: cla: no

#169 Add best practice: stop_id is not rider facing
  gtfs/spec/en/reference.md
Labels: cla: no

#172 Fix incorrect reference to routes.route_id in fare_rules.txt
  gtfs/spec/en/reference.md
Labels: cla: yes

#170 Fix #94 - Clarify that GTFS-rt extension field numbers are permanent
  gtfs-realtime/CHANGES.md
Labels: GTFS - RealTime, cla: yes
